### ISSUE TITLE
`reprun`: `cd` command does not work

### ISSUE THREAD

**Issue by yukinko-iwasaki** [worldbank/repkit#22] opened 2024-02-12 18:00 UTC
if the do file contains something like 

`cd "InputData",
`
the working directory does not seem to change in reprun context.

**Comment by bbdaniels** [comment] 2024-03-28 19:02
Can you clarify what is supposed to happen and what happens instead?

**Comment by yukinko-iwasaki** [comment] 2024-03-28 20:27
We had the following script in one of our verification package. 
It tries to change the working directory in the script at the line 41, but the working directory does not seem to change while executing the script via reprun. (I don't think we recommend changing working directory in the script, but packages come in all different shapes and colors.) 

I think the expected behavior is that command cd changes the working directory.

![image](https://github.com/worldbank/repkit/assets/18432543/565028dc-bfa7-412e-b236-b792eddae25a)

**Comment by kbjarkefur** [comment] 2024-04-16 17:29
Seems like this is a duplicate of #31. The issue is the missing `.do` file extension not `cd`.

**Closed by kbjarkefur** 2024-04-16 17:29 UTC
Labels: duplicate, reprun
